title: No Backlogs
description: 'Focus on the essential: the needs of your customer'
url: 'https://nobacklog.co'
baseurl: '/'

page_excerpts: true

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
plugins:
  - jekyll-seo-tag
  - jekyll-feed
